### PR TITLE
 *: Preliminary work on golden text for meido++ and above 

### PR DESCRIPTION
**Pull request by Chiiruno**
This is going to be a work in progress, this PR is not ready for merging right now.

>chiru what the fuck are you doing why gold text?

Anonymous had a good idea to make it only for meido++ and it fits the motif of Umineko since only the "game master" can use golden text, in this case it's really just to prevent ugly gold text everywhere

>chiru the CSS looks like crap on every theme

I know, I'll work on that later

>chiru why in the absolute fuck are you adding another variable in the qtpl files when you could just use c.Post.Auth

I wish I had a better answer, unfortunately this has been extremely finicky and this is the only thing so far that half-way works.
I'm not sure whether you have some sort of special admin privileges for 127.0.0.1 or something, but no matter what I do or what account I log into, it seems to give `position` the admin level.
The good side to it though, is that it's less work on templates/body.go cycle, since we're comparing ints and not strings.

>chiru the server is keeping the golden text after refreshing, even though the client does it correctly

See the above, I'm not sure what I'm doing wrong and need some reviews.

### CODE REVIEW

**Comment by Chiiruno** [comment]
I also went ahead and incremented the package.json and updated package-lock.json, since you made a lot of client changes recently.
Not gonna touch the C++ client until we know exactly what's going on with that.

**Comment by bakape** [comment]
Yeah, I'm not going to add a third colour tag. At this point might as well just merge this with red and black into custom colour tags. Also, not giving staff any more bling.

**Comment by Chiiruno** [comment]
Custom color tags was something I honestly wanted to avoid, since that's just gonna make the shitposting go all the way to the moon.
Gold text makes sense for staff, but we could make it BO-only I guess.

**Comment by bakape** [comment]
I'm saying that at this point there is no sense to have 3 separate colour
tags and avoid the custom ones. And making it staff-only is a categorical
no.

**Comment by Chiiruno** [comment]
Hm, maybe a better idea would to make gold text OP-only then?
That would satisfy the ability to do Umineko RPs at least.
Should be easier to implement too.
I'm still a bit conflicted about custom color tags, it seems silly, and everyone is going to do special snowflake bullshit with that waaay worse than what we've seen with red/blue.

**Comment by Chiiruno** [comment]
Ah, I mean the OP IP, per thread, not JUST in the OP.

**Comment by Chiiruno** [comment]
That's fine, honestly I agree.
I wasn't trying to give the staff unwarranted abilities, I just wanted to implement something I thought might have been cool.
I don't know if I really want gold text to be available on an unrestricted basis, but if you're alright or neutral about it, I'll whip up a poll on meguca I guess.

**Comment by bakape** [comment]
It will be behind a board-level flag anyway. Those who choose to rot can do so.

**Comment by Chiiruno** [comment]
That's a relief. `¯\_(ツ)_/¯`
image

**Pull request closed without merging**
