### PR TITLE
client, server: refactor Now Playing banner

### PR DESCRIPTION
**Pull request by Kamuso**
It should now be reasonably easy to add/remove options for the now playing banner. This would have been useful back when Chiru had an icecast radio, so if something like that comes back or if Ryuu adds a http endpoint to for his stream information, then they could be added as options, too.
I wanted to keep storing the user's selection under a single local storage key, so now there's code for that kind of thing. The image search options could be stored like this, with a chunky migration function.
If anyone complains about the new look of the banner, it can be mostly reverted with this custom css ``#banner-center {display:flex;}``
The ``ui/options.ts`` change is a bug fix. Thanks for reading my essay.

### CODE REVIEW

**Comment by Kamuso** [comment]
Oh, and I have another pr ready for when you want to have some fun. I want to keep it a secret until then, though.

**Comment by bakape** [comment]
I'll take a look at this on the weekend.

**Comment by bakape** [comment]
Adjusted banner CSS. Otherwise, thanks!

**Comment by bakape** [comment]
Settings and meido panels broke with this commit. Reverthing them in master. Feel free to revert the revert and fix in a different PR.

**Pull request merged**
