### PR TITLE
client, server: Do not rely on the CORS proxy for HookTube video title

### PR DESCRIPTION
**Pull request by Chiiruno**

### CODE REVIEW

**Comment by bakape** [comment]
Still WIP?

**Comment by Chiiruno** [comment]
Usually unless I state otherwise, it's ready for merging.
Yeah, it's all good, unless you see something wrong with it.

**Comment by bakape** [comment]
Can I trust this not to crash the client?

**Comment by Chiiruno** [comment]
It hasn't so far.

**Pull request merged**
