### PR TITLE
common: Ignore ytdl signature token parsing error

### LINKED ISSUE #855: Another youtube embed error
```
 internal server error: YouTube [VzpRh-ZE9Mo]: Error parsing signature tokens: common.StatusError{Err:(*errors.errorString)(0xc4205aed40), Code:500}
```

Please either fix or add to ignored errors. Maybe we really should switch back to noembed? Youtube seems to be a pain in the ass.

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #855
This is likely a ytdl issue, so we can just censor the error.

### CODE REVIEW

**Comment by bakape** [comment]
But this still means these embeds won't work on the client-side, correct?

**Comment by Chiiruno** [comment]
It returns non-200, so it just uses noembed.

**Comment by bakape** [comment]
Oh, Okay. I don't quite like the inconsistency but fine for now.

**Comment by Chiiruno** [comment]
It could be better, yeah, but it's better than some things not working.
The only real way to fix it would be creating an application without a browser, unfortunately.
Or just totally revert to noembed, but I really, really dislike YouTube JS, and think live video or other errors are the only acceptable compromise.

**Pull request merged**
