### PR TITLE
client, templates: Round time properly

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes the incorrect ban times.
It is rounding, so if you do 4 hours and 29 minutes, you will get 4 hours, and 5 hours with 4 hours and 31 minutes. 4 hours and 30 minutes (in the field) will result in 4 hours, because by it is actually 4 hours, 29 minutes and 59 seconds.

### CODE REVIEW

**Comment by Chiiruno** [comment]
So, the test is failing because apparently https://github.com/pierrec/lz4 just did a breaking change with https://github.com/pierrec/lz4/issues/33
Would it be possible to have travis use go 1.11?
Same for my other PR.

**Comment by bakape** [comment]
I'll take a look come the weekend. Feel free to pile up PRs till then.

**Comment by Chiiruno** [comment]
You could probably just merge both and it would be fine, I tested both pretty thoroughly.
Do what you feel is best though, of course.

**Comment by bakape** [comment]
I need to be made to be more thorough in reviewing.

**Comment by bakape** [comment]
You know what I meant.

**Pull request merged**
