### PR TITLE
Add flashing colors to dice rolls

### PR DESCRIPTION
**Pull request by dasdgdafg**
Dice are only formatted if there are at least 2 sides per die, and the maximum possible total was at least 10.  ie \#10d1 would not be formatted, but \#5d2 could be.  The flashing animations go on for about 10 seconds then stop, because CSS animations can cause a lot of CPU usage.

Rolling a 1 makes the roll brown.
Rolling the maximum value makes the roll pink.
Rolling dubs makes the die blue (trips are yellow, quads are green, quints are rainbow).
Rolling a 69 or 6969 makes the roll light pink.
Rolling a 7777 on a d7777 makes the roll rainbow and adds a special message.

### CODE REVIEW

**Comment by dasdgdafg** [comment]
screenshot from 2018-01-14 00-13-08
Example of what the dice look like.

**Comment by bakape** [comment]
Seems to be working fine, so my only concern is the navy roll. But I don't know, if there is a point to the 7777 rainbow without the navy-tan context.

**Comment by dasdgdafg** [comment]
I've removed the Navy-specific case.  So now if you roll a 7777 on a d7777 it will be flashing pink, like all other max rolls.

**Comment by bakape** [comment]
Okay, seems fine now.

**Pull request merged**
