### PR TITLE
Gallery mode

### PR DESCRIPTION
**Pull request by the8472**
adds: 
* css class to posts with images
* keyboard shortcut to apply style that hides all non-image posts
* keyboard nav to jump through posts

### CODE REVIEW

**Comment by bakape** [comment]
Thanks. Code seems fine at first glance. I'll test and merge it later today.

**Comment by bakape** [comment]
Broken on board pages. Throws exceptions, if an empty hash is set. Will fix my shitty URL parsing tomorrow.

**Comment by the8472** [comment]
Latest commit should avoid setting empty hashes. The previous code wasn't accurate enough in filtering out non-post article elements.
Board index is fixed too by traversing all posts instead of only those within a single parent element.

**Comment by bakape** [comment]
I fixed and added a note about language packs. See 773b7ce0793fae7b47ec2fa9108bf841851eee5c.
Let me merge this commit and test.

**Comment by bakape** [comment]
close #236

**Pull request merged**
