### PR TITLE
imager: Reject image sekritposts

### LINKED ISSUE #1050: Scrub sekritpost from images
I actually like image sekritposting, but instead of retarded autism wars, let's just scrub it on upload receive.

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #1050
Not working at the moment, seems like I can't write to multipart.file and I'm not really sure what to do.
Also not sure about optimizations, I'm not liking some of these potentially big copy operations.

### CODE REVIEW

**Comment by Chiiruno** [comment]
Well, since I'm already going full-retard, at anon's request, perhaps pipe the purified image back into an in-house HTTP request if secretposting is detected so one pass is removal, the next is actual upload.

**Comment by Chiiruno** [comment]
If you don't have any ideas, don't close this, I'll just change this to reject the upload instead.

**Comment by Chiiruno** [comment]
actually fuck it, I'll just change it, this is gonna be a slow mess if I try to have meguca be a scrubbing service

**Comment by Chiiruno** [comment]
Not really sure if it's worth the time implementing heuristics to detect variation of 'secret' or the numbers behind it, or the possible long string of plaintext behind that.
Thoughts? It's doable, but I feel it wouldn't do much.

**Comment by chiya-chan** [comment]
You could take the last n bytes of the file for some small n and check how many of those bytes are ascii characters, how many are ascii digits, and assign a score. You could do this for each range between 1 and n as well.

**Comment by bakape** [comment]
You can, if you want, but I don't see much benefit and a risk of false
positives.

**Comment by bakape** [comment]
Like I said on the issue, this might be not worth it.

**Comment by Chiiruno** [comment]
Well, if heuristics are out and there's nothing left to do, ready for merge.

**Pull request merged**
