### PR TITLE
Improve findapng and change it to work with streams

### PR DESCRIPTION
**Pull request by reiclone**
Only C++ implemntation, needs all the JS part to work.
This is the code I used to test it http://pastebin.com/TSsC2xMY.
We should stop reading the file upon getting anything different than 0.
I think javascript is the one who frees the buffer so I didn't do it.

About the implementation: after initializing the object you can call Detect(buffer)
this will return: 0 - If it didn't find anything in the buffer
                       1 - If the file is an apng
                       2 - if the file is a normal png and not an apng
It can also throw an exception when the argument given isn't a buffer.

### CODE REVIEW

**Comment by bakape** [comment]
>We should stop reading the file upon getting anything different than 0.

We will have the same stream piped into 3-4 different functions. Well, I have to write it first and extra optimisations can be made after. Will get to it this evening/tomorrow.

**Comment by bakape** [comment]
I think I've finalised the JS in the [imager-streams](https://github.com/bakape/meguca/commit/b8f7c748407dc728d08550c87c79104425977738) branch. Can you improve something more, since we have the logic now or we good?

**Comment by reiclone** [comment]
I don't really know what more to improve, As it is right now we are just reading the id and the length of the chunks and just until we find one of the two relevant chunks. I could avoid throwing an exception on bad arguments if you think that's better, but I think that's about it.

**Comment by bakape** [comment]
Alright then. I'll finish rewriting imager and merge it all into master.

**Comment by bakape** [comment]
Thanks for the work, btw. I really appreciate it.

**Pull request merged**
