### PR TITLE
Material theme

### PR DESCRIPTION
**Pull request by Soreil**
There are some things I want to add but it is a workable theme at the moment.

### CODE REVIEW

**Comment by bakape** [comment]
screenshot - 020416 - 01 01 48
Don't you think the fonts are far too big to remain usable?

**Comment by Soreil** [comment]
You are right on them being big, a little smaller should be fine but not as small as usual.
I'll tweak it a little.
I was also thinking of trimming left and right margin to 3 or 4% instead of 5%

But the big fonts are super pretty on my poor low DPI monitor and poor eyes, I'll give 13 instead of 14 a shot

**Comment by Soreil** [comment]
I think this should be sufficient size wise.

**Comment by bakape** [comment]
screenshot - 020416 - 15 35 58
Found something after deploying it.
Also, did the + thing with the reply button not work out?

**Pull request merged**
