### PR TITLE
imager: Accept secret posts

### PR DESCRIPTION
**Pull request by Chiiruno**

### CODE REVIEW

**Comment by Chiiruno** [comment]
No point in rejecting secret posts, since we allow pasting images, that also duplicate images on-disk effectively.
Perhaps more sophisticated deduplication is needed in imager.

**Comment by Chiiruno** [comment]
Client-side option to reject or warn before downloading a secret image might be a good idea, though.

**Comment by bakape** [comment]
>Client-side option to reject or warn before downloading a secret image
might be a good idea, though.
What for?

**Comment by Chiiruno** [comment]
So users don't have to download duplicates of the same image but with a secret post inserted, or they know of it at least before downloading.
I'm thinking of even a client-side scrub feature, although maybe that should be in the userscript itself.

**Comment by Chiiruno** [comment]
Related https://github.com/GoatSalad/megukascript/issues/59

**Comment by bakape** [comment]
This sounds more like something that should go strictly into the
userscript.

**Comment by Chiiruno** [comment]
Yeah, that's what I've been working on for the last few days, including an overhaul of the userscript.

**Pull request merged**
