### PR TITLE
client: More usable quoting and pasting

### LINKED ISSUE #435: More  usable quoting
>When quoting a post it always inserts the backlink at the end of the textarea. Inserting it at the cursor would be better. And when the clicking the link opens a new reply form it might also make sense to insert a newline.

### LINKED ISSUE #600: Quote all lines of pasted text, if first line is qouted

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #435 
Fixes #600
I chose to not make a newline if the post form is opened by clicking an ID, because you may want to do ">>324532 >>324533 >>324534", etc.
From what I can tell from the testing, this is a nice little QoL improvement.

### CODE REVIEW

**Comment by Chiiruno** [comment]
Don't merge yet, gonna include #600 into this, rather than a separate PR due to shared functions.

**Comment by Chiiruno** [comment]
Fixes #600
Ready for review and merging.

**Comment by Chiiruno** [comment]
It's a big change.

**Comment by Chiiruno** [comment]
Is this for pasting or for addreference?
Both?

**Comment by Chiiruno** [comment]
If it's pasting, this is intentional, it's not meant to do a double newline, only single, unless you decide it should.

**Comment by Chiiruno** [comment]
That should do it.

**Comment by Chiiruno** [comment]
Actually, I can't reproduce this, and what I thought was a fix, ended up being unrelated.
I must be tired, could you try rebuilding and see if you can still reproduce this please?

**Comment by bakape** [comment]
Can still reproduce. 

[simplescreenrecorder-2018-09-13_17.11.41.zip](https://github.com/bakape/meguca/files/2379653/simplescreenrecorder-2018-09-13_17.11.41.zip)

**Comment by Chiiruno** [comment]
@bakape That should do it.

**Pull request merged**
