### PR TITLE
(wip) Thread Watcher front-end

### LINKED ISSUE #945: Modal-based thread watcher
Convert current notification-based thread watcher to a modal-based one like with 4chan X. Instead of marking threads as read on notification only mark them read, when explicitly scrolled to bottom of the thread.

### PR DESCRIPTION
**Pull request by Kamuso**
Closes #945
Currently just adds a new button to the banner where you can see some static info on all watched threads. Opening this pr early so no one else starts on the issue independently, and to check some things.

First, I think it would be helpful if notifications had which board the thread belongs to, so I'll add that with this pr.
Second, for the status of watched threads I was thinking of using the meguca favicons. For example, Kyouko for seen threads, Madoka for unseen (You)s etc.
Third, do we need adding threads as watched from this interface?
What do you think?

### CODE REVIEW

**Comment by bakape** [comment]
Excellent. Also, you can create branches on the `bakape/meguca` repo now. That way it is easier for me to review, modify and merge them.

**Comment by bakape** [comment]
>Third, do we need adding threads as watched from this interface?

We could add a "Watch this thread" button, even if that will mean it is in 2 places now.

**Comment by Kamuso** [comment]
>Also, you can create branches on the bakape/meguca repo now.

I'm still pretty new to git. So, I would ``git push`` local branches to your repo instead of mine? Will do.

>We could add a "Watch this thread" button, even if that will mean it is in 2 places now.

Okay. With a textbox for the thread id, I suppose.

How do you feel about the other two suggestions?

**Comment by bakape** [comment]
>With a textbox for the thread id, I suppose.

Why not just put it on the button itself? 

>How do you feel about the other two suggestions?

Greenlit.

**Comment by Kamuso** [comment]
Not sure we're thinking of the same thing.
image
This is the draft interface that shows all watched threads (ignore the data, that was just to test). Should we add the ability to watch other threads to it?

**Comment by bakape** [comment]
How do you wee the thread input working?

**Comment by Kamuso** [comment]
The way it currently does, clicking the toggle on OPs or creating/posting in a thread. I think it's fine as is, but #945 specifies adding threads from the management panel which is why I asked.

**Comment by bakape** [comment]
No need for the adding in the panel then.

**Comment by Kamuso** [comment]
Nearly finished. Need to change the status of threads in the panel whenever they update, but I'm not sure where to do that.

**Comment by bakape** [comment]
There is a click event handler in threadWatcher.ts

**Comment by Chiiruno** [comment]
Do you plan on updating this?

**Comment by Chiiruno** [comment]
Will readdress once new version is up and working.
Or will implement as we go.

**Pull request closed without merging**
