### PR TITLE
*: Small overhaul of logging system, automatic emailing on error

### LINKED ISSUE #707: Optionally send errors to email
Can probably just copy output on the default logger. 
For inspiration: 
https://godoc.org/github.com/go-playground/log/handlers/email
https://github.com/golang/go/wiki/SendingMail

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #707 
There are a few caveats.
- I couldn't make the email password field in the server configuration gui not get the password
- Because of how `log.addHandlers` works, you have to edit your settings, restart, and then you will be emailed your errors
- You might want to adjust what is considered an error, however I think what I put should be decent... There can't be that many image upload errors a day.

### CODE REVIEW

**Comment by bakape** [comment]
>I couldn't make the email password field in the server configuration gui not get the password

What did you mean by this?

>Because of how log.addHandlers works, you have to edit your settings, restart, and then you will be emailed your errors

Can be solved with a mutex and moving logger initialization to `db/config.go:{loadConfigs,updateConfigs}`. I think creating a separate log package under `go/src/meguca/log` with all the locking abstracted away would be best. 

>You might want to adjust what is considered an error, however I think what I put should be decent... There can't be that many image upload errors a day.

That can wait.

**Comment by Chiiruno** [comment]
>What did you mean by this?

Please compile the commit and get into the server configuration tab, put a password in the email password field, save, and then come back. If you inspect it with F12 you'll see that it fetches the password, instead of acting like all other password fields and NOT fetching the password.

>Can be solved with a mutex and moving logger initialization to db/config.go:

That makes things a lot easier. I think I remember having some memory violation doing something like that, but I'll try again.

**Comment by Chiiruno** [comment]
Oh, that memory error was because I had it in /config, cool.

**Comment by Chiiruno** [comment]
Ah, I guess I explained the thing about `log.addHandlers` wrong.
It adds a handler and you're unable to remove the handler, so that's why I did it once-per database initialization, so it doesn't spam your email with duplicate errors.
If I put it into `db/config.go:{loadConfigs,updateConfigs}`, it will add a _new_ handler each time, thus adding +1 email error each time. In other words, you have 5 errors and 5 handlers, you now have 25 errors in your mailbox, 20 of them are duplicates.

**Comment by Chiiruno** [comment]
I can move the initialization to `db/config.go:loadConfigs`, but updateConfigs I can't until we figure out the potential spam problem.

**Comment by bakape** [comment]
Question: Why go through all this complexity, if we can just take https://golang.org/pkg/log/#SetOutput and override it to copy errors to the email as well? Probably best to have it copy to a function that dynamically fetches configs and the default logger right before `server/init.go:startWebServer()`

**Comment by bakape** [comment]
I think this will break deamonization. That relies on the default logger. 

>As far as I can see, unless you plan on changing the error email every day or something, this should work fine as a once-per-initialization handler.

Fair enough. 

>Is there a way to made the email password field more secure?

Only, if you want to rewrite server configuration. Best just leave it like that.

**Comment by bakape** [comment]
Wait. Daemonization works, but you get output like this: 
```
2018-05-19 19:32:23.798186423+03:00 ESC[34m  INFOESC[0m Server started ------------------------------------
2018-05-19 19:32:23.878551031+03:00 ESC[34m  INFOESC[0m listening on 127.0.0.1:8000
```
Could you remove that extra formatting? Surely a config does that.

**Comment by Chiiruno** [comment]
I'm not surprised that daemonization works, the console handler I imagine handles that.
I'll look into the output.

**Comment by bakape** [comment]
Tell me, when it's done.

**Comment by Chiiruno** [comment]
You can use it right now if you want, I put a `TODO:` in the update function for whenever it becomes possible to live update the `eLog` handler's email settings.

**Comment by Chiiruno** [comment]
I have a [pull up for the log](https://github.com/go-playground/log/pull/20) so we can enable the update function.

**Comment by Chiiruno** [comment]
Also for future reference, I give `mLog` it's own `Daemonized` bool to avoid circular imports.

**Comment by bakape** [comment]
screenshot_20180525_221724
Chiru, I think you mixed up the subject and body fields.

**Pull request merged**
