### PR TITLE
Added red/blue text as user usable

### PR DESCRIPTION
**Pull request by Chiiruno**
Idea was inspired by an anon mentioning red/blue truth from Umineko no Naku Koro ni, might be fun for some /seacats/-type boards.
Aside from the weird color tag duplication when blue is nested into red in (non-breaking, no real bloat), everything seems to work out pretty good and I've tested it with the other encasings.

### CODE REVIEW

**Comment by bakape** [comment]
Can you also patch the coming C++ client fr this?

**Comment by bakape** [comment]
On second thought, I'm really not sure this should be included into meguca at all. Extra fromatiing that is not related to some idiomatic notation like programming code, scientific fomulae, etc. is probably needless. You would also need to make it look good on ALL current and future themes. 

I'll consider  this some more.

**Comment by Chiiruno** [comment]
I can try an patch the C++ client, although I'm completely unfamiliar with it.
As for whether it should be included it or not, I think if you don't want to make it a global default, you could make this an option with a simple `if` statement and a check box for board management for certain boards that want it or times any board wants it enabled.
On the other hand, IMO red/blue text is pretty basic and I don't think it'll hurt anything even if it was global. Shouldn't be too difficult to make it look decent on all themes... maybe a [glowing](https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_text-shadow_neon) effect like in the actual sound novel?

Do you have any idea what to do about the duplication? I've always had a hard time grasping other's code and some input from the main programmer would be a lot of help.

**Comment by Chiiruno** [comment]
...or just make it a board option, I guess it would probably be too much disconformity on regular boards.

**Comment by bakape** [comment]
>...or just make it a board option, I guess it would probably be too much disconformity on regular boards.

Probably for the best. 

>maybe a glowing effect like in anime?

Maybe. It would spare the need to adapt separate CSS for each theme.

>Do you have any idea what to do about the duplication? 

What are you talking about exactly?

**Comment by Chiiruno** [comment]
Look at nested formatting in body_test.go. I probably just misunderstood the code somewhere.
I'll work on making it a board option and a saner formatting. Maybe ^r ^b.

**Comment by bakape** [comment]
Probably here https://github.com/bakape/meguca/pull/667/files#diff-0c0ee16c33ee188c75410a4a5fbcbceeR228 . All tags must retain a hierarchy and you don't have the same order of descendance here as in other places.

**Comment by Chiiruno** [comment]
It doesn't seem like that was the issue, thanks for pointing that out though.
What's your opinion on per-thread for this instead of per-board?
And if so, should it be default on, or default off?

**Comment by bakape** [comment]
Per thread is probably needless complexity in thread creation.

For per board configs look at:
https://github.com/bakape/meguca/blob/master/go/src/meguca/config/structs.go#L47
https://github.com/bakape/meguca/blob/master/go/src/meguca/db/config.go
https://github.com/bakape/meguca/blob/master/go/src/meguca/db/init.go#L39

**Comment by Chiiruno** [comment]
Fair enough. I'll be back with a commit.

**Comment by Chiiruno** [comment]
Don't pull yet, that commit is broken.
`go test --race -p 1 meguca/...
ok      meguca  1.147s
?       meguca/assets   [no test files]
ok      meguca/auth     (cached)
ok      meguca/cache    (cached)
?       meguca/common   [no test files]
ok      meguca/config   (cached)
ok      meguca/db       (cached)
?       meguca/geoip    [no test files]
ok      meguca/imager   (cached)
ok      meguca/imager/assets    1.012s
?       meguca/lang     [no test files]
ok      meguca/parser   (cached)
2018/03/20 18:43:16 server: 192.0.2.1: struct key not found: RbText
goroutine 204 [running]:
runtime/debug.Stack(0xc42017c500, 0xc41160, 0x9)
        /nix/store/r7p21cmhq0jimq2f8c8y5sm2vqg2ap99-go-1.10/share/go/src/runtime/debug/stack.go:24 +0xb5
meguca/server.logError(0xc42017c500, 0xb8bf80, 0xc420546880)
        /home/okina/Downloads/meguca/go/src/meguca/server/util.go:72 +0x84
meguca/server.text500(0xccada0, 0xc4200e4b40, 0xc42017c500, 0xb8bf80, 0xc420546880)
        /home/okina/Downloads/meguca/go/src/meguca/server/util.go:92 +0xe5
github.com/dimfeld/httptreemux.(*TreeMux).serveHTTPPanic(0xc42025a1e0, 0xccada0, 0xc4200e4b40, 0xc42017c500)
        /home/okina/go/src/github.com/dimfeld/httptreemux/router.go:68 +0xb6
panic(0xb8bf80, 0xc420546880)
        /nix/store/r7p21cmhq0jimq2f8c8y5sm2vqg2ap99-go-1.10/share/go/src/runtime/panic.go:505 +0x24a
meguca/templates.configurationTable(0xbe4120, 0xc4205525a0, 0x99, 0xc415ea, 0xe, 0x1, 0x0, 0x0)
        /home/okina/Downloads/meguca/go/src/meguca/templates/forms.go:31 +0x554
meguca/templates.ConfigureBoard(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/okina/Downloads/meguca/go/src/meguca/templates/forms.go:16 +0xce
meguca/server.boardConfigurationForm(0xccada0, 0xc4200e4b40, 0xc42017c600)
        /home/okina/Downloads/meguca/go/src/meguca/server/html.go:219 +0x106
github.com/dimfeld/httptreemux.(*ContextGroup).Handle.func1(0xccada0, 0xc4200e4b40, 0xc42017c500, 0xc4204ee690)
        /home/okina/go/src/github.com/dimfeld/httptreemux/context.go:55 +0x69
github.com/dimfeld/httptreemux.(*TreeMux).ServeLookupResult(0xc42025a1e0, 0xccada0, 0xc4200e4b40, 0xc42017c500, 0xc8, 0xc420256400, 0xc4204ee690, 0x0)
        /home/okina/go/src/github.com/dimfeld/httptreemux/router.go:247 +0x196
github.com/dimfeld/httptreemux.(*TreeMux).ServeHTTP(0xc42025a1e0, 0xccada0, 0xc4200e4b40, 0xc42017c500)
        /home/okina/go/src/github.com/dimfeld/httptreemux/router.go:268 +0x156
meguca/server.TestBoardConfigurationForm(0xc420484780)
        /home/okina/Downloads/meguca/go/src/meguca/server/html_test.go:167 +0x4c1
testing.tRunner(0xc420484780, 0xc65b90)
        /nix/store/r7p21cmhq0jimq2f8c8y5sm2vqg2ap99-go-1.10/share/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
        /nix/store/r7p21cmhq0jimq2f8c8y5sm2vqg2ap99-go-1.10/share/go/src/testing/testing.go:824 +0x565

--- FAIL: TestBoardConfigurationForm (0.86s)
        html_test.go:168: unexpected status code: 200 : 500
FAIL
FAIL    meguca/server   23.217s
ok      meguca/templates        (cached)
?       meguca/test     [no test files]
ok      meguca/util     (cached)
ok      meguca/websockets       (cached)
ok      meguca/websockets/feeds (cached)
make: *** [Makefile:93: test] Error 1`

Maybe you might know why it keeps transforming 'rbText' to 'RbText' when I try to configure the board.
Also, on templates/body.go, is there a way to get the board config so I can put a simple `if` statement to get it to work once this is fixed?

**Comment by bakape** [comment]
I know the cause. Let me get home to point you to the problem.

**Comment by bakape** [comment]
https://github.com/bakape/meguca/blob/master/go/src/meguca/templates/forms.go#L27 right here transforms the key for configuration form generation. Sadly this means you are forced to use CamelCase property identifiers, which would be `RbText` in your case.

**Comment by Chiiruno** [comment]
That did it. I would have never guessed that was even thing with what seemed like a type.
Now, to actually make it work, on templates/body.go, I'm thinking using this line `r, err := prepared["get_all_board_configs"].Query()`and `err = r.Scan(` from `func loadBoardConfigs() error {` in db/config.go should work to get the board configuration for RbText.

**Comment by Chiiruno** [comment]
[wtf.patch](https://github.com/bakape/meguca/files/1840952/wtf.txt)
Just curious if anything I did in this patch file here was anything even close to what was supposed to be done.

**Comment by bakape** [comment]
You don't need to send me patches. As long as it is pushed to git I can
merge it into a branch myself.
I'll take a look some time today or tomorrow.

**Comment by Chiiruno** [comment]
I sent a patch because it was a really bad attempt at making everything work and I didn't want to make it a commit since it didnt' work. I just wanted to see if I was doing anything half-right in it.

The problem I'm having is that I can't figure out how to do two things: get the state of rbText SQL or perhaps memory into templates/body.go, and also how to make sure that state also gets to the client so that render/body.ts can figure out whether or not to render the red/blue text.

**Comment by bakape** [comment]
Okay. Fuck this shit. I'm rewriting the buulshit we have right now to decent SQL query builder lib. Hold on a day or 2.

**Comment by Chiiruno** [comment]
Haha sorry for the trouble. I had no idea this would end up being so complicated.

**Comment by bakape** [comment]
I've been meaning to do this for a while.

**Comment by bakape** [comment]
This will take longer than I thought. Relevant branch: [dev/refactor-sql](https://github.com/bakape/meguca/tree/dev/refactor-sql).

**Comment by Chiiruno** [comment]
I'm closing this pull request and will come back with a new, working one.
Especially now after all these long years, I finally learned how to actually use git.

**Comment by Chiiruno** [comment]
#680

**Pull request closed without merging**
