### PR TITLE
client: fix malformed css

### PR DESCRIPTION
**Pull request by Kamuso**
``translate3d`` was being ignored, so now things will be even more unreadable.

### CODE REVIEW

**Comment by bakape** [comment]
Why were statics updated?

**Comment by Kamuso** [comment]
I don't know. Never really payed much attention to that. I ran ``migrate_lang.js`` and ``make generate`` to see what would happen and statics changed again, but nothing else seemed to change.  That's what the test commit was.

**Comment by bakape** [comment]
There should be no changes to statiks from client JS changes. You are committing dirty state from yourn branch (or maybe just version difference). Please remove the `statik.go` updates just to be sure.

**Comment by Kamuso** [comment]
Ok, good to go.

**Comment by bakape** [comment]
Thanks!

**Pull request merged**
