### PR TITLE
Fat thread optimizations

### PR DESCRIPTION
**Pull request by the8472**
This _should_ reduce the memory and CPU spikes when opening a previously unvisited fat thread and jumping towards the end. Locally I only checked that it still works, needs to be profiled on the live system.

### CODE REVIEW

**Comment by bakape** [comment]
Oh, these actually make a lot of sense. I'll review these in detail some time this week, when I have more free time.

**Comment by bakape** [comment]
This got me thinking, our seen post detection just might be needlessly complex and we could improve performance further by using a simpler seen post detection algorithm: consider everything in the same thread with a post ID lower than the lowest scrolled to post as seen. This would remove the need for massive DB write spam enteriley at the cost of less granularity. Thoughts?

**Comment by the8472** [comment]
The issue might be gallery mode. You see a lot of posts that way without seeing those in between.
If we ignore that (less granularity as you say), then yes.

But we would still have to store it on scroll, which would still lead to update storms when implemented naively.

**Comment by bakape** [comment]
Deferral to once a second would help there.

**Comment by bakape** [comment]
Make that 500 ms.

**Comment by the8472** [comment]
Obviously, I am doing the same here after all. But I think that's basically a rewrite of the seen feature instead of just fixing the resource consumption of the current logic, i.e. beyond the scope of this PR.

**Comment by bakape** [comment]
Nevertheless I will  merge this PR and base my work on yours. Much appreciated!

**Comment by the8472** [comment]
Perf looks good. No more OOMs on big threads.

**Pull request merged**
