### PR TITLE
assets, docs, server: Specifiable background video directory

### LINKED ISSUE #1020: Have meguca search path for background videos
In the case of nixos, specifically my meguca package, where the www directory is immutable, it would be good to be able to point meguca to a directory in which meguca can read and serve to the user.
Related: https://github.com/NixOS/nixpkgs/pull/57527

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #1020
Turns out I can't really do anything other than what I've already done for the www issue as far as Nix is concerned, but whatever.
This should be good for admins that have a stupid amount of background videos and want to put them on another drive or some shit, I guess.
No need to keep the www/videos directory, meguca will now auto-generate it.
I don't want meido, power gets to my head.

### CODE REVIEW

**Comment by bakape** [comment]
Why does nix need this exactly?

**Comment by Chiiruno** [comment]
Because I was symlinking the www directory from the nix store and that place is immutable, so I had to make a www directory and then symlink everything inside of the nix store www directory into the new www directory, with videos folder being the one that's not symlinked.
I just did this PR because I was already half-way through it before realizing I'm retarded.

**Comment by Chiiruno** [comment]
Also this might be a good platform for eventually making multiple video directories readable by meguca, to save some miniscule amount of space since dude symlinks lmao.

**Comment by bakape** [comment]
I don't see a point in this. It adds extra complexity for little gain. Disk space limitations should be bypassed by file system mounts.

**Pull request closed without merging**
