### PR TITLE
css: Hide banner overflow, unhide if mouse hover

### LINKED ISSUE #728: 'synced' will get pushed down if song title is too long
Or if the window is too small.
image

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #728
Well, it's a bit of an ugly solution, but it'll work until you can do something smarter.

### CODE REVIEW

**Comment by bakape** [comment]
Wait, I remember doing something similar for Hydron recently. https://github.com/bakape/hydron/blob/master/client/main.less#L5-L27
Basically, have to make the banner a flexbox with no horizontal margins and padding and then make all the elements inside have `margin-${left/right}: auto`, according to the side they should flow to. Then have the middle one have `overflow-x: auto`. 

Can you do this or should I?

**Comment by Chiiruno** [comment]
@bakape If you want to do it right now or otherwise tonight? You should do it, since you're way better with CSS.
If it's gonna take a while, I'll try my hand.

**Comment by bakape** [comment]
I'll make an issue for this, but do try to remind me, if you see me on meguca.

**Comment by Chiiruno** [comment]
Okay.

**Pull request closed without merging**
