### PR TITLE
client, templates: Various youtube/hooktube embed fixes

### PR DESCRIPTION
**Pull request by Chiiruno**
Another day, another pull request.

### CODE REVIEW

**Comment by Chiiruno** [comment]
Don't pull yet, I messed something up.

**Comment by Chiiruno** [comment]
Ok, that'll do it.
This is ready for merging again.

**Comment by Chiiruno** [comment]
I'm not really sure why travis is failing this, but it compiles, tests correctly, and works on my end.

**Comment by bakape** [comment]
I'll restart the last master build and see, if anything changes.

**Comment by Chiiruno** [comment]
Go ahead and restart this one too, travis may have fixed their shit since master seems to be building.

**Comment by Chiiruno** [comment]
Actually since coveralls is a thing now, and if you did the stuff in the site, I'll force push and restart it and maybe coveralls will show too.

**Pull request merged**
