### PR TITLE
calculate favicons from post visibility and scrolling

### PR DESCRIPTION
**Pull request by the8472**
at some point in the future this could use [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) instead of recomputing on scroll, but that's still too new for now. But recomputation is capped to once every 200ms and skips already-seen posts.

### CODE REVIEW

**Comment by bakape** [comment]
Wouldn't you want to persist these? Perhaps a new ObjectStore in IndexedDB and the appropriate additions to `client/state.js`. Then a check against a Set of already seen posts in the `client/posts.Post` constructor.

**Comment by the8472** [comment]
question, where do the existing posts from the DOM get integrated into the JS state? It seems like they're not yet counted towards unread posts when opening a long thread.

**Comment by bakape** [comment]
If you mean posts, that are rendered on the server, those are extracted in `client/page`. The specific functions are in `client/page/common`.

**Comment by the8472** [comment]
it should be fairly close to 4chanX's behavior now

**Comment by bakape** [comment]
Does not account for cross-page navigation. The count stays the same, when navigating between threads/boards. Perhaps add a callback to `client.state.page.onChange("thread")`?

**Comment by the8472** [comment]
done

**Comment by bakape** [comment]
Seems fine now. Good work!

**Pull request merged**
