### PR TITLE
*: Server-side option to disable client-side showing live bans

### LINKED ISSUE #984: Server-side option to disable showing client-side live bans
This kills the memeban.
Supersedes #983

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #984
This is a bit hard to test, but from what I can tell, it works.

### CODE REVIEW

**Comment by Chiiruno** [comment]
Actually, judging by how this is currently working, I may want to go ahead and get rid of the message from the templates too.

**Comment by Chiiruno** [comment]
templates: Remove ban message **if** DisableLiveBan is enabled*
Ready for review.

**Comment by bakape** [comment]
Why would we need this?

**Comment by Chiiruno** [comment]
In case the site admin gets sick of dumb memebans, or the dumb meta that accompanies them.
Kill the source of the attention, kill the cause behind the cancer.
At least this way, the site owner can have a choice.

**Comment by bakape** [comment]
I agree that ban duration minimums and the unban restrictions should be a
policy instead of hardcoded. However, this simply kills moderation
transparency.

**Comment by Chiiruno** [comment]
Not really, there's mod-log for that.

**Comment by Chiiruno** [comment]
On another note, I was wondering about your thoughts on making this board-specific instead?
Different boards have different culture, with different meidos.

**Comment by bakape** [comment]
You have to explicitly look into the modlog. This is very prominent as a
censorship vector. I want the codebase to bend people towards transparent
moderation and instill the notion of moderation staff being civil servants
- not the superuser elite.

**Comment by Chiiruno** [comment]
Thus why this is toggle function.
Turn it off for a few days to get rid of the attention whoring, as well as the meta, turn it back on later.

**Comment by bakape** [comment]
That is how I personally would use it, but not other people.

**Comment by Chiiruno** [comment]
Perhaps, but I think it's universal enough to warrant the merge.
With live posting, starts live banning, and other live moderation, sometimes it might be necessary to turn stuff like live bans showing off for a bit.
I'm just not entirely sure whether this should be site-level or board-level.
As for other meguca admins, if they really want to be a botnet, they'll just code it in.

**Comment by bakape** [comment]
Okay, I'll review tomorrow. Office party.

**Comment by Chiiruno** [comment]
Any reason why?

**Comment by bakape** [comment]
Transparency.

**Comment by Chiiruno** [comment]
You realize live bans weren't always a feature, right?
Oh well, maybe this should have been upgraded to a bit more something severe anyway.
Thoughts on toggling off/on the entire live-moderation system?

**Comment by Chiiruno** [comment]
My reasoning is that this is happening anyway with meme deletes, and will eventually go down to literally anything a meido can do.
I guess that's my fault too, but if we're gonna go down this rabbit hole, might as well do it right.
We either need strict rurus for meidos, or have the option to eliminate the instant gratification attention whoring. (meme deletes/bans/whatever)
I guess I'm just throwing out bits, take whatever you think is a good idea.

**Comment by bakape** [comment]
It must be always immediately aware to the users that moderation has
occurred.

**Comment by Chiiruno** [comment]
Alright, that's fair, and clear enough.

**Pull request closed without merging**
